### ISSUE TITLE
Lagg spike

### ISSUE THREAD

**Issue by solo5star** [organization/ServerReading#1]
화면에 정보를 띄우는 플러그인은 클라이언트에 많은 렉을 유발합니다. Tip의 경우 한번 보냈을때 화면에 약 2초동안 표시되니 40tick 마다 정보를 보내어 클라이언트의 부담을 줄이는게 좋다고 생각합니다.

**Comment by ghost** [comment]
@angelless

**Comment by ghost** [comment]
@solo5star 
개선하겠습니다.
이슈넣어주셔서 감사합니다.
